#!/bin/bash

#source workspace_versions.sh

# get version to build from docker tag set in Docker Hub build settings
JAVAVERSION=$(printf $DOCKER_TAG | sed 's/java//g')
NODEVERSION=$(printf $DOCKER_TAG | sed 's/node//g')
PYTHON3VERSION=$(printf $DOCKER_TAG | sed 's/python//g')
RUBYVERSION=$(printf $DOCKER_TAG | sed 's/ruby//g')

echo "DOCKER_TAG $DOCKER_TAG"
echo "ARGTOBEWRITTEN $ARGTOBEWRITTEN"
echo "JAVAVERSION $JAVAVERSION"
echo "NODEVERSION $NODEVERSION"
echo "PYTHON3VERSION $PYTHON3VERSION"
echo "RUBYVERSION $RUBYVERSION"

docker build \
--build-arg ARGTOBEWRITTEN="aaa" \
--build-arg JAVAVERSION=${JAVAVERSION} \
--build-arg NODEVERSION=${NODEVERSION} \
--build-arg PYTHON3VERSION=${PYTHON3VERSION} \
--build-arg RUBYVERSION=${RUBYVERSION} \
-f $DOCKERFILE_PATH -t $IMAGE_NAME .
